### ISSUE TITLE
Reasons people don't want to use the megamenu

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#1]
Statcan, InfoBase, and others don't want to use the megamenu because the categories are similar to those in their content and people become confused.

Maybe others have the same concern (Recalls).

Transactional scenarios (where someone is in the middle of trying to complete a task) are cases where content owners are concerned the menu will distract people.

Some orgs are trying to maintain a distinct brand for their property and think the megamenu detracts from that. 

Some orgs aren't sure how to adapt their current navigation since they'll lose a persistent global nav menu dedicated to their content.

**Comment by pcwsmith** [comment]
oops I spazzed there for a sec
