### ISSUE TITLE
grids/whitespace: many pages have awk "holes" in their layouts - heard complaints from stakeholders. But is this an issue for people being able to use the pages.

### ISSUE THREAD

**Issue by pcwsmith** [gc-proto/design-refresh#10]
Here's an example of weird holes and strange alignment.

Is this something that can be dealt with globally via design update or do people just need to take more care in designing their pages?

**Comment by pcwsmith** [comment]
![alginment and whitespace example](https://user-images.githubusercontent.com/5454117/40253349-63a6a252-5aad-11e8-9741-c923777d9847.png)

**Comment by patlaj** [comment]
Related to #16

**Comment by pcwsmith** [comment]
now that this has been aligned w issue #16, I will close this issue
