### ISSUE TITLE
Wrapper variants for transactional apps (CDTS) have opportunities for testing and refinement

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#13]
Dave had been working on this - can we find where he was?

**Comment by ericcoops** [comment]
![ssl-templates services gc ca_app_cls_wet_gcweb_v4_0_26_cdts_apptop_apptop_all-en shtml 1](https://user-images.githubusercontent.com/24705426/40944130-a1578f0e-6821-11e8-9262-7df05ce5af06.png)

Other examples are here: https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_26/cdts/appTop/apptop-en.shtml 

Asked Kamla Fisher for user testing evidence on those patterns

**Comment by pcwsmith** [comment]
Another angle on transactions/apps... There are also those that have left in the sitewide global nav, but then added in their own menu underneath, e.g. Job Bank with a double hamburger:
![image](https://user-images.githubusercontent.com/5454117/41126600-152fbdec-6a76-11e8-8d80-314143dac5f7.png)


It kinda feels like they were trying to find a way to solve the "local nav within the app" issue in their own way...

**Comment by ericcoops** [comment]
Met with CDTS to see their new prototype for transactional apps
They have a "Dashboard of tasks" pattern that lists links to all the steps in any given process. CDTS is very excited about this pattern, but it has not been implemented yet. 
**Unsure whether left nav or top nav works best**
"Card" approach works better for mobile, possible responsive design
Allows custom links in the footer, though there is little demand for custom footer links. 
Application name in blue bar is sufficient identifier
CDTS wants to beta test **bound progress bar**, not enough resources
Collaborative Labour Market Information being displayed using **interactive map**
Chatbox help feature is upcoming
