### ISSUE TITLE
Known issues with the current grid system

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#16]
And how can we address them?

**Comment by pcwsmith** [comment]
examples of grids from other govs:

https://designsystem.digital.gov/components/grids/

https://design.cms.gov/layout/grid/

http://govuk-elements.herokuapp.com/layout/

https://www.ontario.ca/document/ontario-design-guide/layout

I think I got the number 12 from looking at the US examples before...

**Comment by pcwsmith** [comment]
moved to in progress.

1. @jmealing showed us some of the weird alignments, she will provide more deets or screencaps here.

2. this should be the focus of the grids aspect of this project - cleaning up the weirdness in alignments in the current grid system.

**Comment by jmealing** [comment]
![weird-div-alignment](https://user-images.githubusercontent.com/31008799/41820978-14ec0eaa-77a8-11e8-9889-829a6300e904.png)

Offices, by Phone & International/non-residents are all set to "col-md-4" (x3 = 12 columns), yet they do not span the same distance as the main col-md-12 container leaving a big gap at the end.

**Comment by jmealing** [comment]
![bad-alignments](https://user-images.githubusercontent.com/31008799/42043290-1719cd88-7ac4-11e8-83f6-509de8f19e3a.png)

Weird alignments of boxes

**Comment by jmealing** [comment]
Pockets of awkward white space and false floor:

https://www.canada.ca/en/agriculture-agri-food/corporate/lawrence-macaulay.html

![false-floor](https://user-images.githubusercontent.com/31008799/42043630-e8fa1b46-7ac4-11e8-8e82-8b635b796024.png)

**Comment by jmealing** [comment]
Whole page width text-heavy content...

https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/gi-196/gst-hst-commercial-ride-sharing-services.html

![12-col-walls-of-text](https://user-images.githubusercontent.com/31008799/42044262-8a530af6-7ac6-11e8-8bdf-0820f0f5075e.png)

**Comment by jmealing** [comment]
Features easily mis-align:

https://www.canada.ca/en/services/health/healthy-living.html

![mis-aligned-content](https://user-images.githubusercontent.com/31008799/42044385-e4131176-7ac6-11e8-976d-9720190b574d.png)

**Comment by jmealing** [comment]
Mobile navigation goes to the bottom in some templates:

https://www.canada.ca/en/employment-social-development/programs/ei/ei-list/ei-employers.html

![disappearing-mobile-nav-2](https://user-images.githubusercontent.com/31008799/42044596-6a2d09b0-7ac7-11e8-90ab-81fadba3a1bd.png)
![disappearing-mobile-nav](https://user-images.githubusercontent.com/31008799/42044603-6c23d03c-7ac7-11e8-8d70-f90817e71623.png)

**Comment by jmealing** [comment]
Minister layout:
https://www.canada.ca/en/government/ministers/diane-lebouthillier.html

![minister-layout](https://user-images.githubusercontent.com/31008799/42044764-cf2ef986-7ac7-11e8-9fc8-9019d9630582.png)

**Comment by jmealing** [comment]
Gaps, bad text width layout:

https://www.canada.ca/en/public-health/services/canadian-immunization-guide.html

![just-no](https://user-images.githubusercontent.com/31008799/42045037-8abc9bc2-7ac8-11e8-83a0-7479f0c69eb9.png)

**Comment by jmealing** [comment]
FIP gets pushed down by Language selector:

![dedicated-row-pushes-fip](https://user-images.githubusercontent.com/31008799/42046214-630d4a06-7acb-11e8-81fd-c9383ab5fcf8.png)

**Comment by jmealing** [comment]
Bad alignment in search:

![bad-alignment-search](https://user-images.githubusercontent.com/31008799/42046236-6fe3fe50-7acb-11e8-831f-86c58bafc4a1.png)

**Comment by DK-TBS** [comment]
The big gaps have been an awful problem for us for a long time - and they get so much worse when an author doesn't happen to need an element, and leaves out a sidebar block, or a photo or whatever.  This is why I'm seriously thinking that we should look into trying to linearize the new design as much as possible.  One rule:  easy to follow:  more important stuff goes above the less important stuff.  Sidebars in only certain circumstances, etc - or better yet GONE.  But I'm totally thinking off the top of my head here, I'm probably ignoring lots of considerations and loads of data  :)
