### ISSUE TITLE
The Canada wordmark is a clearer signal as a "Home" link than the GC signature

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#20]

**Comment by pcwsmith** [comment]
see also #12 which covers some of the FIP policy issues involved

**Comment by patlaj** [comment]
Yeah it's a duplicate

**Comment by patlaj** [comment]
OK not really a duplicate - it IS more effective based on the results of our tests:

https://docs.google.com/presentation/d/1okxBUPwVQm2I8Yo2ZusB-JJSqk950xm22QYILGe6nYQ/edit#slide=id.g3d8bf19af5_0_23

...not the same as meaning it should be used.

**Comment by realredd** [comment]
Crazy thought incoming...
USA.gov
Gov.uk
Canada**.ca**  <<

If we're pushing on using the wordmark over the FIP, which is the right direction in my opinion, could we not go further and add the ".ca" to it.
