### ISSUE TITLE
Can we use the Canada wordmark at the top of webpages and as the home link?

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#21]
Apparently this was the original plan for Canada.ca, but it was changed at the last minute. 

Is there a policy reason that prevents this use? 

Note that in the Federal Identity Program manual, it states:

"The wordmark is also highly recognized by the Canadian public as a symbol of the Government of Canada."

That means it would possibly lend some credibility to the website to include it in a more visible location.

**Comment by pcwsmith** [comment]
this is a dupe essentially of issue #12 - so closing
