### ISSUE TITLE
There's no strong usability guideline for sans serif vs. serif fonts

### ISSUE THREAD

**Issue by pcwsmith** [gc-proto/design-refresh#23]
So Medium uses a serif font in articles, sans serif on landing pages. So I was wondering, why, when everyone knows that sans serif is better on screen…. 

Well, this thinking appears to be outdated. The “sans serif is more readable online” dogma is a leftover from the days of truly crappy screens (those crazy days back in the 90s).

Now, there really isn’t a compelling usability argument either way:

“However, given the research data, the difference in reading speed between serif and sans serif is apparently quite small. Thus, **there's no strong usability guideline in favor of using one or the other, so you can make the choice based on other considerations** — such as branding or the mood communicated by a particular typographical style.”

https://www.nngroup.com/articles/serif-vs-sans-serif-fonts-hd-screens/  (2012)

**Comment by DK-TBS** [comment]
It's helpful to have headings stand out from body text in some way other than size alone... and that's what gets a lot of designers into pairing serif with sans-serif fonts, one for headings and one for body text.  

I don't have evidence, but my eyeballs always seem to tell me that sans-serif works better in body text, and that nice serif fonts tend to look really handsome at larger sizes.  But I do think that we'll find that people will be able to more easily scan (by identifying headers more readily) if we use different typefaces for headers vs body.  Not an easy thing to test, though.
