### ISSUE TITLE
Sans serif isn't necessarily seen as more modern and simple

### ISSUE THREAD

**Issue by pcwsmith** [gc-proto/design-refresh#24]
So ok, let's say the decision on font is more about brand and voice than about usability concerns (see #23) - seems to me that we stick to sans serif if we want to communicate modern and simple?

Although - is there research to confirm how sans serif fonts are perceived vs how serif fonts are perceived?

There's a lot of this kind of opinion out there in the designosphere:

"People tend to use Serif typefaces for something quite serious. This is because of their traditional and conservative look and feel."
https://medium.freecodecamp.org/how-typography-determines-readability-serif-vs-sans-serif-and-how-to-combine-fonts-629a51ad8cce

"Sans serif typefaces are considered more modern.... The mood and feelings most associated with sans serif typefaces are modern, friendly, direct, clean and minimal."
https://designshack.net/articles/typography/serif-vs-sans-serif-fonts-is-one-really-better-than-the-other/
  
And these opinions _feel_ about right... is there empirical evidence to support this?

**Comment by patlaj** [comment]
A few years ago this may have been the case, but lately serif fonts are being used more often. 

Factors other than the font itself have a bigger impact on the sense of modernity.
