### ISSUE TITLE
List of sites that are avoiding the common look

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#3]
http://www.statcan.gc.ca/eng/start (megamenu only)

https://digital.canada.ca

http://www.veterans.gc.ca/eng/services-vac-acc

https://impact.canada.ca/

https://www.canada.ca/en/services/youth.html

https://www.canada.ca/en/privy-council/corporate/clerk/publications/twenty-fifth-annual-report-prime-minister-public-service.html

https://www.canada.ca/en/employment-social-development/services/canada-service-corps.html

https://youthaction.ca

https://www.ic.gc.ca/app/scr/innovation
(Pretty closely follows, but has blue background)

**Comment by pcwsmith** [comment]
https://youthaction.ca

**Comment by pcwsmith** [comment]
@patlaj worth interviewing folks who made any of these?

**Comment by patlaj** [comment]
Yes! That’s a great idea. Let’s strategize tomorrow on how to
bon-judgementally hear from the people who designed these non standard
sites

**Comment by patlaj** [comment]
Partner site to YouthAction:

https://www.canada.ca/en/services/youth.html

Interestingly built on Canada.ca but clearly with more flexibility than most of the pages there.

**Comment by patlaj** [comment]
Canada Service Corps
https://www.canada.ca/en/employment-social-development/services/canada-service-corps.html
