### ISSUE TITLE
Current Canada.ca typography is too small and not visually pleasing.

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#4]
We've seen people pinch and zoom on mobile but less likely to with our revised font and size. (Usability testing)

Line length is well beyond recommended to be easily readable. (Rubina H research, others)

**Comment by pcwsmith** [comment]
someone mentioned today that theyd seen stuff recently recommending line lengths even < 90ish chars, can we dig that up & linkity-link pls

**Comment by patlaj** [comment]
Some sources with their conclusions:

https://baymard.com/blog/line-length-readability - 50-60 (or up to 75) characters per line, including spaces

http://webtypography.net/2.1.2 - 45-75, 66 ideal

https://practicaltypography.com/line-length.html 45-90

https://en.wikipedia.org/wiki/Line_length - In order for on-screen text to have both the best speed and comprehension possible about 55 cpl should be used

**Comment by pcwsmith** [comment]
wow those are a *lot* shorter than 95ish
